name: Sync multiple branches
on:
  push:
    branches: [ "dev" ]
      
jobs:
  
  test-backend:
    defaults:
      run:
        shell: bash
        working-directory: ./backends
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  
      - name: check the depence
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
  
  
  
  
