name: Sync multiple branches
on:
  push:
    branches: [ "dev" ]
      
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: ./backend
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  
      - name: check the depence
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
  
  
