name: Sync multiple branches
on:
  push:
    branches: [ "dev" ]
      
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: test backend
        working-directory: backend
      - run: npm install
      - run: npm test
      - name: test frontend
        working-directory: frontend
      - run: npm install
      - run: npm test
      - name: merge to the main branch
      - uses: actions/checkout@master
      - name: Merge dev -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
