name: Sync multiple branches
on:
  push:
    branches: [ "dev" ]
      
jobs:
  job1:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  
      - run: npm install
      - run: npm test
  job2:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  
      - run: npm install
      - run: npm test
     
  job3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge dev -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: main
          
  
       
  
  
  
